### PR TITLE
Merge ConcreteProvider with Provider

### PR DESCRIPTION
**Pull request by yiiliveext**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Tests pass?   | ✔️

### CODE REVIEW

**Comment by samdark** [comment]
Looks like Provider now can do everything ConcreteProvider can. Is that correct?

**Comment by samdark** [comment]
@romm how do you like these changes?

**Comment by romm** [comment]
Indeed now both providers do the same job. I'm not sure I really see the point of these changes when the wanted feature is already present in the library. The [CompositeProvider](https://github.com/yiisoft/event-dispatcher/blob/master/src/Provider/CompositeProvider.php) can be used if features from both the default provider and the concrete one are needed.

@yiiliveext possible to explain why you'd need these changes?

**Comment by yiiliveext** [comment]
> @yiiliveext possible to explain why you'd need these changes?

See https://github.com/yiisoft/yii-web/pull/238

**Comment by samdark** [comment]
@romm it's basically simpler when it comes to what @yiiliveext posted above. In https://github.com/yiisoft/event-dispatcher/issues/10 you've mentioned "or create a new basic provider with this feature which would allow the usage of the aggregate listener provider". Thinking more about it I really wonder about your use case for preferring composite provider for it.

**Comment by romm** [comment]
@samdark this is not really about my use case but more of an implementation choice.

From my experience, adding a new argument to an existing class means more difficult maintainability in the future (the class now has several goals, it breaks the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single-responsibility_principle), it adds more lines of code, etc.). Whereas decoupling these two different functionalities in two different classes means easier maintenance.

I tend to prefer a more functional programming approach, but I agree with you, the PHP world is more at ease with the proposed solution here.

This is up to you, both solution work. You have to find the right balance between easy usage and easy maintenance, this would be a choice tightly bound to the framework coding policy I guess. 🙂

**Comment by romm** [comment]
I took a look at yiisoft/yii-web#238 and I think I begin to understand why merging both providers is proposed.

@yiiliveext may I ask an example of usage of `Yiisoft\Yii\Web\Config\ EventManager` so that I can better understand the need?

**Comment by yiiliveext** [comment]
> @yiiliveext may I ask an example of usage of `Yiisoft\Yii\Web\Config\EventManager` so that I can better understand the need?
See
https://github.com/yiisoft/yii-debug/blob/78dd90d57442b6d54aca322fbb7e783dcdd6edfa/config/events.php
and
https://github.com/yiisoft/yii-demo/blob/a22f1324f0a686f2215713a82941f89b1927e5c9/public/index.php

**Comment by romm** [comment]
Ok thank you for the links.

I took some time to analyze more deeply the issue, and I still believe both providers make sense in their own way. I also think that the default implementation given to the container should be a CompositeProvider, which allows third-party users to easily attach their own provider(s); it may be a big breaking change though, what do you guys think about this:

```patch
Index: vendor/yiisoft/yii-web/src/Config/EventManager.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- vendor/yiisoft/yii-web/src/Config/EventManager.php	(revision ceb3d0157fdd751d860083791e5808a92d8ea385)
+++ vendor/yiisoft/yii-web/src/Config/EventManager.php	(date 1585875892451)
@@ -4,25 +4,32 @@
 
 use Psr\Container\ContainerInterface;
 use Psr\EventDispatcher\ListenerProviderInterface;
+use Yiisoft\EventDispatcher\Provider\CompositeProvider;
 use Yiisoft\EventDispatcher\Provider\ConcreteProvider;
 use Yiisoft\EventDispatcher\Provider\Provider;
 
 class EventManager
 {
-    private ListenerProviderInterface $listenerProvider;
+    private Provider $provider;
+
+    private ConcreteProvider $concreteProvider;
 
     private ContainerInterface $container;
 
     public function __construct(ListenerProviderInterface $listenerProvider, ContainerInterface $container)
     {
-        if (!($listenerProvider instanceof Provider || $listenerProvider instanceof ConcreteProvider)) {
+        if (! ($listenerProvider instanceof CompositeProvider)) {
             throw new \InvalidArgumentException(
-                'Listener provider must be instance of Yiisoft\EventDispatcher\Provider or
-                Yiisoft\EventDispatcher\ConcreteProvider.'
+                'Listener provider must be instance of Yiisoft\EventDispatcher\CompositeProvider'
             );
         }
-        $this->listenerProvider = $listenerProvider;
+
         $this->container = $container;
+        $this->provider = new Provider();
+        $this->concreteProvider = new ConcreteProvider();
+
+        $listenerProvider->attach($this->provider);
+        $listenerProvider->attach($this->concreteProvider);
     }
 
     public function registerListeners(array $listeners): void
@@ -36,13 +43,13 @@
                     if (is_array($callable) && !is_object($callable[0])) {
                         $callable = [$this->container->get($callable[0]), $callable[1]];
                     }
-                    $this->listenerProvider->attach($callable, $event);
+                    $this->concreteProvider->attach($event, $callable);
                 }
             } else {
                 if (!is_callable($listener)) {
                     throw new \RuntimeException('Listener must be a callable.');
                 }
-                $this->listenerProvider->attach($listener);
+                $this->provider->attach($listener);
             }
         }
     }
Index: config/web.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- config/web.php	(revision a22f1324f0a686f2215713a82941f89b1927e5c9)
+++ config/web.php	(date 1585875792588)
@@ -1,5 +1,6 @@
 <?php
 
+use Yiisoft\EventDispatcher\Provider\CompositeProvider;
 use Yiisoft\Yii\Web\Data\DataResponseFormatterInterface;
 use Yiisoft\Yii\Web\Data\Formatter\HtmlDataResponseFormatter;
 use App\Factory\AppRouterFactory;
@@ -17,7 +18,6 @@
 use Psr\Http\Message\UriFactoryInterface;
 use Yiisoft\Auth\IdentityRepositoryInterface;
 use Yiisoft\EventDispatcher\Dispatcher\Dispatcher;
-use Yiisoft\EventDispatcher\Provider\Provider;
 use Yiisoft\Router\FastRoute\UrlGenerator;
 use Yiisoft\Router\Group;
 use Yiisoft\Router\RouteCollectorInterface;
@@ -70,7 +70,7 @@
     // ],
 
     // Event dispatcher:
-    ListenerProviderInterface::class => Provider::class,
+    ListenerProviderInterface::class => CompositeProvider::class,
     EventDispatcherInterface::class => Dispatcher::class,
 
     // View:

```

**Comment by yiiliveext** [comment]
> I took some time to analyze more deeply the issue, and I still believe both providers make sense in their own way. 

There is no own way, both providers do the same, they add a listener for some event. The difference is a method of setting EventName parameter, it is a direct set or a set as the type of parameter in a callable. 
>I also think that the default implementation given to the container should be a CompositeProvider, which allows third-party users to easily attach their own provider(s); it may be a big breaking change though, what do you guys think about this:

CompositeProvider is a bad practice because in this case, we must divide our module listeners between two providers, internal listeners, and external listeners. The better way is using CompositeEventDispatcher. The third-party components create own EventDispatcher with its own Provider and then attach it to the main CompositeEventDispatcher of the app. In this way, it defends event listeners from fake global events.

**Comment by romm** [comment]
Ok you convinced me. 😉

**Comment by yiiliveext** [comment]
> Ok you convinced me.

We can leave CompositeProvider, maybe there are some use cases for it, we'll but remove ConcreateProvidder. Are you agree?

**Comment by romm** [comment]
Yes no problem you can do it, thanks for asking anyway. 🙂

**Comment by yiiliveext** [comment]
> Yes no problem you can do it, thanks for asking anyway.

Thanks

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
